name: cms isp dab demo
on:
  push

defaults:
  run:
    working-directory: ./default_python/

env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
  TEST: blahblahbalh

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    environment: dev
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For test
        id: validate
        run: |
          databricks bundle validate -t dev -p DEFAULT
      - name: Deploy Bundle to dev
        id: deploy
        run: |
          databricks bundle deploy -t dev -p DEFAULT
  
  deploy_prod:
    if: github.ref == 'refs/heads/main'
    environment: prod
    needs: unit_tests
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For prod
        id: validate
        run: |
          databricks bundle validate -t prod -p DEFAULT
      - name: Deploy Bundle to prod
        id: deploy
        run: |
          databricks bundle deploy -t prod -p DEFAULT
